[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1000000
gas_reports = ["CreateFactory"]
fs_permissions = [
	{ access = "read", path = "./out/"},
	{ access = "read-write", path = "deployments" }
]

[profile.default.rpc_endpoints]
mainnet = "${RPC_ETHEREUM}"
sepolia = "${RPC_SEPOLIA}"
optimism = "${RPC_OPTIMISM}"
optimism-sepolia = "${RPC_OPTIMISM_SEPOLIA}"
polygon = "${RPC_POLYGON}"
polygon-amoy = "${RPC_POLYGON_AMOY}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum-sepolia = "${RPC_ARBITRUM_SEPOLIA}"
base = "${RPC_BASE}"
base-sepolia = "${RPC_BASE_SEPOLIA}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }
sepolia = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_SEPOLIA}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM}" }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM_SEPOLIA}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON}" }
polygon-amoy = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON_AMOY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM}" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM_SEPOLIA}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_URL_BASE}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_URL_BASE_SEPOLIA}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
