[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 1000000
gas_reports = ["CreateFactory"]
fs_permissions = [{ access = "read", path = "./out/"}]

[profile.default.rpc_endpoints]
ethereum = "${RPC_ETHEREUM}"
sepolia = "${RPC_SEPOLIA}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }
sepolia = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_SEPOLIA}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
